[package]
name = "gen-target-info"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde-tuple-vec-map = "1.0.1"
serde_json = "1.0.107"
