[package]
name = "gen-windows-sys-binding"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
windows-bindgen = "0.49"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]
