[package]
name = "find-msvc-tools"
version = "0.1.12"
edition.workspace = true
rust-version.workspace = true
description = "Find windows-specific tools, read MSVC versions from the registry and from COM interfaces"
documentation = "https://docs.rs/find-msvc-tools"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true
