name: Publish release

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  release-plz-release:
    if: github.repository_owner == 'rust-lang'
    name: Release-plz release
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      pull-requests: write
      contents: write
      id-token: write     # Required for OIDC token exchange
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - name: Run release-plz
        uses: release-plz/action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5.131
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
