name: Publish release

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  release-plz-release:
    if: github.repository_owner == 'rust-lang'
    name: Release-plz release
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      pull-requests: write
      contents: write
      id-token: write     # Required for OIDC token exchange
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # v1
        with:
          toolchain: stable
      - name: Run release-plz
        uses: release-plz/action@b8d6b54b02889ff2ae2bb82e8b57c3a8fc1683a5 # v0.5.139
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
