name: Publish release

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  release-plz-release:
    if: github.repository_owner == 'rust-lang'
    name: Release-plz release
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      pull-requests: write
      contents: write
      id-token: write     # Required for OIDC token exchange
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - name: Run release-plz
        uses: release-plz/action@1528104d2ca23787631a1c1f022abb64b34c1e11 # v0.5.128
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
