name: Regenerate target info

on:
  workflow_dispatch: # Allow running on-demand
  schedule:
    - cron: '0 3 * * 4'
  push:
    branches:
      - 'main'
    paths:
      - 'dev-tools/gen-target-info/**'

permissions: {}

jobs:
  regenerate:
    if: github.repository_owner == 'rust-lang'
    name: Regenerate target info & Open Pull Request if necessary
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - name: Generate branch name
        run: |
          git checkout -b regenerate-target-info-${{ github.run_id }}

      - name: Get msrv
        uses: ./.github/actions/get-msrv

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          cache: false
          toolchain: ${{ env.MSRV }}, stable, nightly

      - name: Create lockfile
        run: cargo update

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-all-crates: 'true'
      - name: Regenerate target info
        run: cargo run -p gen-target-info

      - name: Detect changes
        id: changes
        run:
          # This output boolean tells us if the dependencies have actually changed
          echo "count=$(git status --porcelain=v1 | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        # Only push if changes exist
        if: steps.changes.outputs.count > 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Regenerate target info"
          git push origin HEAD

      - name: Open pull request if needed
        if: steps.changes.outputs.count > 0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --title "Update src/target/generated.rs" --body "Automatically regenerated in CI" --head $(git branch --show-current)
